apiVersion: apps/v1
kind: Deployment
metadata:
    name: check-out-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-out-microservice
  template:
    metadata:
      name: check-out-microservice
      labels:
        app: check-out-microservice
    spec:
      containers:
        - image: dnbias/hroom:check-out-microservice
          name: check-out-microservice-app
          imagePullPolicy: Always
          env:
              - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
                value: "true"
      restartPolicy: Always
