apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: landlord-microservice
  name: landlord-microservice
spec:
  ports:
      - port: 80
        targetPort: 8080
  selector:
    app: landlord-microservice
  type: LoadBalancer
