apiVersion: apps/v1
kind: Deployment
metadata:
    name: landlord-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landlord-microservice
  template:
    metadata:
      name: landlord-microservice
      labels:
        app: landlord-microservice
    spec:
      containers:
        - image: dnbias/hroom:landlord-microservice
          name: landlord-microservice-app
          imagePullPolicy: Always
          env:
              - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
                value: "true"
      restartPolicy: Always
