version: '3'

services:
  hroom-parent:
    image: springboot-docker-compose-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-hroom-parent
    ports:
      - "8081:8081"