version: '3'

services:
  server-app:
    build:
      context: ./hroom-server
      dockerfile: Dockerfile
    image: hroom-server-image
    restart: on-failure
    ports:
      - "8080:8080"
    container_name: server-app
    depends_on:
      - mariadb-app
    networks:
      - backend

  web-app:
    build:
      context: ./hroom-web
      dockerfile: Dockerfile
    image: hroom-web-image
    ports:
      - "80:80"
    container_name: web-app
    depends_on:
      - server-app
    networks:
      - frontend

  # connettersi da locale al server mariadb di docker tramite localhost:3308
  # user: hroom
  # pass: hroom
  mariadb-app:
    image: mariadb:latest
    container_name: mariadb-app
    environment:
      MYSQL_DATABASE: hroom_database
      MYSQL_USER: hroom
      MYSQL_PASSWORD: hroom
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3308:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - backend

volumes:
  mariadb-data: {}

networks:
  backend: {}
  frontend: {}
