version: '3'

services:
  server-app:
    build:
      context: ./hroom-server
      dockerfile: Dockerfile
    image: hroom-server-image
    restart: on-failure
    ports:
      - "8080:8080"
    container_name: server-app
    depends_on:
      - mysql-app
    networks:
      - backend

  web-app:
    build:
      context: ./hroom-web
      dockerfile: Dockerfile
    image: hroom-web-image
    ports:
      - "80:80"
    container_name: web-app
    depends_on:
      - server-app
    networks:
      - frontend

  mysql-app:
    image: mysql:8.0
    restart: on-failure
    container_name: mysql-app
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=hroom
      - MYSQL_USER=hroomuser
      - MYSQL_PASSWORD=hroompassword
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  mysql-db: {}

networks:
  backend: {}
  frontend: {}