apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/hroom-backend: "true"
    io.kompose.service: config-server
  name: config-server
spec:
  hostname: config-server
  containers:
    - image: dnbias/hroom:config-server
      name: config-server
      imagePullPolicy: Always
      ports:
        - containerPort: 9191
          hostPort: 9191
          protocol: TCP
  restartPolicy: OnFailure
