apiVersion: apps/v1
kind: Deployment
metadata:
    name: admin-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-microservice
  template:
    metadata:
      name: admin-microservice
      labels:
        app: admin-microservice
    spec:
      containers:
        - image: dnbias/hroom:admin-microservice
          name: admin-microservice-app
          imagePullPolicy: Always
          # env:
          #     - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
          #       value: "true"
      restartPolicy: Always
