apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  ports:
    - name: "9191"
      port: 9191
      targetPort: 9191
  selector:
    io.kompose.service: config-server
  type: LoadBalancer
