apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: discovery-server-app
  name: discovery-server-app
spec:
  ports:
    - name: "1111"
      port: 1111
      targetPort: 1111
  selector:
    io.kompose.service: discovery-server-app
  type: LoadBalancer
