apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/hroom-backend: "true"
    io.kompose.service: discovery-server-app
  name: discovery-server-app
spec:
  hostname: discovery-server
  containers:
    - image: dnbias/hroom:discovery-server
      name: discovery-server
      ports:
        - containerPort: 1111
          hostPort: 1111
          protocol: TCP
  initContainers:
    - name: init-discovery-server
      image: busybox:stable
      command: ['sh', '-c', "sleep 4"]
