apiVersion: apps/v1
kind: Deployment
metadata:
    name: feedback-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-microservice
  template:
    metadata:
      name: feedback-microservice
      labels:
        app: feedback-microservice
    spec:
      containers:
        - image: dnbias/hroom:feedback-microservice
          name: feedback-microservice-app
          imagePullPolicy: Always
          env:
              - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
                value: "true"
      restartPolicy: Always
