apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mariadb-app
  name: mariadb-app
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3308
  selector:
    io.kompose.service: mariadb-app
