apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mariadb-insertion-data
  name: mariadb-insertion-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
