apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: reservation-microservice
  name: reservation-microservice
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8080
  selector:
    io.kompose.service: reservation-microservice
