apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/hroom-backend: "true"
    io.kompose.service: tenant-microservice
  name: tenant-microservice
spec:
  containers:
    - image: dnbias/hroom:tenant-microservice
      name: tenant-microservice-app
      ports:
        - containerPort: 8080
          hostPort: 8082
          protocol: TCP
  restartPolicy: OnFailure
