apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      name: user-microservice
      labels:
        app: user-microservice
    spec:
      containers:
        - image: dnbias/hroom:user-microservice
          name: user-microservice-app
          imagePullPolicy: Always
          env:
              - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
                value: "true"
      restartPolicy: Always
