apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app.kubernetes.io/name: config-server
  ports:
  - name: config-server-port
    protocol: TCP
    port: 9191
    targetPort: config-port
